# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7486180c3ca87cbe41b394312bb96506bd54f5e421cf2785e38b24fc39bf520fa4f554664624f1c6b540a44e396b2558a85bb97d15c5542209a110967a8bc327

test:
  secret_key_base: 9ed32dc7c1876e41d76a8dd09aeb2872a56989e050810b77012283fa57de2ac79536b1a3f8c2788fbd1bd43abe39681a53a3b8ad675648e8866786296493b36f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
